# Colors
background #001419
foreground #839496
cursor #708183
selection_background #073642
color0 #002731
color8 #001e26
color1 #d01b24
color9 #bd3612
color2 #728905
color10 #465a61
color3 #a57705
color11 #52676f
color4 #2075c7
color12 #708183
color5 #c61b6e
color13 #5856b9
color6 #259185
color14 #81908f
color7 #e9e2cb
color15 #fcf4dc
selection_foreground #93a1a1

# Fonts
font_family       FiraCode Nerd Font Mono
bold_font         FiraCode Nerd Font Mono Bold
#italic_font       auto
#bold_italic_font  auto

font_size 14.0
disable_ligatures never

# Cursor
mouse_hide_await      3.0
cursor_beam_thickness 1.5

# Window
wayland_titlebar_color    #001419
remember_window_size      no
initial_window_width      1080
initial_window_height     720

# Other
force_ltr no
adjust_line_height 9
adjust_line_width 0
adjust_baseline 0
box_drawing_scale 0.001, 1, 1.5, 2
scrollback_lines 2000
