# Inspirado no tema Nigh Owl -> https://github.com/sdras/night-owl-vscode-theme

[colors.primary]
background = "#011627"
foreground = "#d6deeb"

[colors.normal]
black = "#011627"
red = "#ef5350"
green = "#22da6e"
yellow = "#c5e478"
blue = "#82aaff"
magenta = "#c792ea"
cyan = "#21c7a8"
white = "#ffffff"

[colors.bright]
black = "#575656"
red = "#ef5350"
green = "#22da6e"
yellow = "#ffeb95"
blue = "#82aaff"
magenta = "#c792ea"
cyan = "#7fdbca"
white = "#ffffff"

# Configurações gerais dos terminal

[window]
startup_mode = "Windowed"
dynamic_title = true
decorations_theme_variant = "Dark"
decorations = "None"
dimensions = { columns = 100, lines = 26 }

[font]
normal = { family = "Iosevka Nerd Font Mono", style = "Regular" }
bold = { family = "Iosevka Nerd Font Mono", style = "Bold" }
italic = { family = "Iosevka Nerd Font Mono", style = "Italic" }
bold_italic = { family = "Iosevka Nerd Font Mono", style = "Bold Italic" }
size = 16

[cursor]
style = { shape = "Block", blinking = "Always" }

[mouse]
hide_when_typing = true
